version: '3'

services:
  app:
    build: .
    container_name: vacancies-app
    volumes:
      - .:/home/node/app
      - ./node_modules/:/home/node/app/node_modules
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
